GET http://localhost:8080/rest/api/clients
Accept: application/json

###
POST http://localhost:8080/rest/api/clients/addClient
Accept: application/json

###
POST http://localhost:8080/rest/api/clients/addClient
Accept: application/json
Content-Type: application/json

{
  "clientId":"testId",
  "firstName":"TestFirstName",
  "lastName":"TestLastName",
  "address":{
    "city":"TestCity",
    "street":"TestStreet",
    "streetNr":"2137"
  }
}


###
POST http://localhost:8080/rest/api/clients/addClient
Accept: application/json
Content-Type: application/json

{
    "clientId":"niewiadomo",
    "firstName":"123",
    "lastName":"Doe",
    "address": {
      "city":"Łupinki Łużyckie",
      "street":"łączna",
      "streetNr":53
    }
}


###






