version: '3.8'

networks:
  cassandra:

services:
  cassandra1:
    image: docker.io/bitnami/cassandra:latest
    hostname: cass1
    ports:
      - 7000:7000
      - 9042:9042
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    volumes:
      - ./cassandra1_data:/bitnami
    environment: &environment
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=nbd
      - CASSANDRA_PASSWORD=nbdpassword
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M

  cassandra2:
    image: docker.io/bitnami/cassandra:latest
    hostname: cass2
    ports:
      - 7001:7000
      - 9043:9042
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    volumes:
            - ./cassandra2_data:/bitnami
    environment: *environment
