version: '3.9'

networks:
  cassandra:

volumes:
  cassandra1_data:
  cassandra2_data:

services:
  cassandra1:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandra1
    ports:
      - "7000:7000"
      - "9042:9042"
    networks:
      - cassandra
    volumes:
      - cassandra1_data:/bitnami
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=1000M
      - HEAP_NEWSIZE=200M
# cassandra cassandra (login password)
  cassandra2:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandra2
    ports:
      - "7001:7000"
      - "9043:9042"
    networks:
      - cassandra
    volumes:
          - cassandra2_data:/bitnami
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=1000M
      - HEAP_NEWSIZE=200M